app = "errmon"
primary_region = "gru"
kill_signal = "SIGQUIT"       # https://nginx.org/en/docs/control.html
kill_timeout = 60
console_command = "/bin/bash"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 4096
    soft_limit = 2024

  [[http_service.checks]]
    grace_period = "5s"
    interval = "10s"
    timeout = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    [http_service.checks.headers]
      Host = "health.local"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
