name: errmon-client

services:
  devcontainer:
    container_name: errmon-client-devcontainer
    image: errmon-client-devcontainer:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    restart: no
    env_file: ../.env
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK:?err}
      HISTFILE: /root/history.d/.bash_history
    volumes:
      - ${SSH_AUTH_SOCK:?err}:${SSH_AUTH_SOCK:?err}:ro
      - ../:/app
      - ./dotfiles/.bashrc:/root/.bashrc:ro
      - npm-cache:/root/.npm
      - history:/root/history.d
      - node-modules:/app/node_modules
    deploy:
      resources:
        limits:
          memory: 4G

  runner:
    extends: devcontainer
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

volumes:
  history:
  npm-cache:
  node-modules:
